--- 
- name: Install mysql 
  hosts: mysql 
  become: yes 
  tasks: 
  - name: install mysql-server 
    ansible.builtin.dnf: 
      name: mysql-server 
      state: installed 
    
  - name: start mysql and enable 
    ansible.builtin.service: 
      name: mysqld
      state: started 
      enabled: yes 

  - name: connect to mysql server 
    community.mysql.mysql_info:
      login_user: root 
      login_password: ExpenseApp@1 
      login_host: mysql.tridev.online
    register: mysql_info
  
  - name: print the output for the mysql login info 
    ansible.builtin.debug: 
      msg: "MySQL info: {{ mysql_info }}"
